require 'pathname'
require File.dirname(__FILE__) + '/cotta/impl/io_chain'
require File.dirname(__FILE__) + '/cotta/cotta_dir'
require File.dirname(__FILE__) + '/cotta/cotta_file'
require File.dirname(__FILE__) + '/cotta/impl/cotta_pathname'
require File.dirname(__FILE__) + '/cotta/cotta'
require File.dirname(__FILE__) + '/cotta/impl/in_memory_system'
require File.dirname(__FILE__) + '/cotta/impl/physical_system'
require File.dirname(__FILE__) + '/cotta/file_not_found_error'
require File.dirname(__FILE__) + '/cotta/impl/command_runner'
require File.dirname(__FILE__) + '/cotta/command_error'
require File.dirname(__FILE__) + '/cotta/command_interface'
require 'pathname'