require File.dirname(__FILE__) + '/cotta/cotta'
require File.dirname(__FILE__) + '/cotta/in_memory_system'
require File.dirname(__FILE__) + '/cotta/io_chain'
require File.dirname(__FILE__) + '/cotta/file_not_found_error'
require File.dirname(__FILE__) + '/cotta/command_runner'
require File.dirname(__FILE__) + '/cotta/command_error'
require File.dirname(__FILE__) + '/cotta/command_interface'
require 'pathname'